### ISSUE TITLE
ARM Architecture

### ISSUE THREAD

**Issue by davidlirving** [davidlirving/Project-Zero-Sector#9]
Current common file only allows for i386, i686 and amd64 arch types. SFML/CEGUI are both available for ARM, no reason to disallow ARM arch type compilers even if we're not directly supporting it.

**Comment by chrisbeamond** [comment]
Added. Note that ARM is completely unsupported and will probably not work.

https://github.com/davidlirving/Project-Zero-Sector/commit/81d7c977622526b978a2807cb3c95e21a7540cab
